### ISSUE TITLE
<pip_dir>/venv_archives is not automatically created 

### ISSUE THREAD

**Issue by akhanf** [pvandyken/kslurm#16]
Looks like the folder <pip_dir>/venv_archives needs to be manually created before running `kpy save ...`

```
(presurfer) [akhanf@gra-login3 presurfer-smk]$ kpy save presurfer
pipdir not set. Please set pipdir using `kslurm config pipdir <directory>`, typically to a project-space or permanent storage directory
(presurfer) [akhanf@gra-login3 presurfer-smk]$ kslurm config pipdir $WHEELHOUSE
(presurfer) [akhanf@gra-login3 presurfer-smk]$ kpy save presurfer
Traceback (most recent call last):
  File "/home/akhanf/.local/bin/kpy", line 8, in <module>
    sys.exit(kpy())
  File "/home/akhanf/.local/pipx/venvs/kslurm/lib/python3.9/site-packages/kslurm/args/command.py", line 60, in wrapper
    func(parsed)  # type: ignore
  File "/home/akhanf/.local/pipx/venvs/kslurm/lib/python3.9/site-packages/kslurm/cli/kpy.py", line 447, in kpy
    command([name, *tail.values])
  File "/home/akhanf/.local/pipx/venvs/kslurm/lib/python3.9/site-packages/kslurm/args/command.py", line 60, in wrapper
    func(parsed)  # type: ignore
  File "/home/akhanf/.local/pipx/venvs/kslurm/lib/python3.9/site-packages/kslurm/cli/kpy.py", line 251, in _save
    venv_cache = VenvCache()
  File "/home/akhanf/.local/pipx/venvs/kslurm/lib/python3.9/site-packages/kslurm/cli/kpy.py", line 98, in __init__
    venvs_re = [
  File "/home/akhanf/.local/pipx/venvs/kslurm/lib/python3.9/site-packages/kslurm/cli/kpy.py", line 98, in <listcomp>
    venvs_re = [
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.9.6/lib/python3.9/pathlib.py", line 1150, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/project/6050199/akhanf/opt/wheelhouse/venv_archives'
```

**Comment by pvandyken** [comment]
Thanks, I'll get a hot fix for this
