### ISSUE TITLE
kpy bash not working for me? 

### ISSUE THREAD

**Issue by akhanf** [pvandyken/kslurm#17]
Any idea what could be the problem here?
```
(presurfer) [akhanf@gra-login3 wheelhouse]$ kpy bash >> ~/.bashrc 
Traceback (most recent call last):
  File "/home/akhanf/.local/bin/kpy", line 8, in <module>
    sys.exit(kpy())
  File "/home/akhanf/.local/pipx/venvs/kslurm/lib/python3.9/site-packages/kslurm/args/command.py", line 60, in wrapper
    func(parsed)  # type: ignore
  File "/home/akhanf/.local/pipx/venvs/kslurm/lib/python3.9/site-packages/kslurm/cli/kpy.py", line 447, in kpy
    command([name, *tail.values])
  File "/home/akhanf/.local/pipx/venvs/kslurm/lib/python3.9/site-packages/kslurm/args/command.py", line 60, in wrapper
    func(parsed)  # type: ignore
TypeError: _bash() takes 0 positional arguments but 1 was given
```

**Comment by pvandyken** [comment]
I caught this the other day, this should be fixed in `v0.3.3`. Could you upgrade and give that a try?
